### ISSUE TITLE
Codec issue

### ISSUE THREAD

**Issue by bfelder** [0xabu/pdfannots#1]
With about half the pdf I try to extract from I get the following error message / or similar:

> UnicodeEncodeError: 'latin-1' codec can't encode character '\u201c' in position 274: ordinal not in range(256)

I suppose an additional UTF-8 specification is needed.

**I have already changed "iso8859-15" to "utf-8" in the get_annots method, yet the issue remains.**

I work on a recent Ubuntu Distro and python 3.6.

**Comment by 0xabu** [comment]
Sorry for the delay. It's hard to respond to this without knowing more. Can you point me at a PDF file which reproduces the problem? Failing that, can you figure out which string conversion is the problematic one (there are many inside pdfminer) and capture the backtrace?

**Comment by bfelder** [comment]
Andrew the bad is on my behalf. The issue is not in your version of pdfannots! I mistook two different files I was keeping in my project folder. And I even pushed the completely wrong one to GitHub in May.  More precisely the bug is related to fpdf another dependency that I added. :-1:  My bad sorry for any trouble.
