### ISSUE TITLE
Extraction of highlighted text fails

### ISSUE THREAD

**Issue by kiran90429** [0xabu/pdfannots#11]

**Comment by kiran90429** [comment]
I'm getting the below result.

## Highlights

 * Page 1: (XXX: missing text!)

 * Page 1: (XXX: missing text!)

 * Page 1: (XXX: missing text!)

**Comment by 0xabu** [comment]
This indicates that the PDF text extraction failed to find any characters in the bounds of the highlight. I would suggest trying the `pdf2txt.py` sample program that's part of the pdfjam library, and see if that produces any output for the relevant text. If not, then it's a possible bug/limitation in pdfjam and should be reported there. If you do get text for this PDF from pdf2txt, then I can look into why we can't extract it if you updload the relevant PDF file.

**Comment by kiran90429** [comment]
Sure, Thanks for the Update. I will try that and update here.

**Comment by 0xabu** [comment]
Not sure why I wrote pdfjam above; I meant pdfminer!

Did you repro this with pdf2txt? Can I close this?

**Comment by kiran90429** [comment]
Sure,  u can close this.
