### ISSUE TITLE
If the filename contain space, it won't be successful run

### ISSUE THREAD

**Issue by jacksparrowFF2** [0xabu/pdfannots#22]
If the filename contain space, it won't be successful run. 

For example, AB.pdf can work correctly, but A B.pdf will fail.

**Comment by 0xabu** [comment]
Thanks for the report! Can you provide the error message or backtrace when it fails?

**Comment by jacksparrowFF2** [comment]
Hi! here is the screenshot, sorry I am late

![image](https://user-images.githubusercontent.com/23632933/64701544-8bce7300-d4db-11e9-8663-dc63414716f9.png)

**Comment by 0xabu** [comment]
You need to escape the filename to prevent it being treated as two arguments. For Windows/CMD, use quotes:
```
C:\src\pdfannots>python pdfannots.py "test file.pdf"
## Highlights
...
```
