### ISSUE TITLE
Is it possible to detect shapes like Lines and Arrows in pdf

### ISSUE THREAD

**Issue by balandongiv** [0xabu/pdfannots#30]
Great works, really appreciate it.

Just curious, is it possible to detect the [shapes like, rectangle, line and arrows ](https://www.pdfannotator.com/en/help/toolslinearrow) using this code, if possible for future improvement?

**Comment by 0xabu** [comment]
Thanks. I think those probably show up in the annotations, yes -- we filter for only a few types of annotations:
https://github.com/0xabu/pdfannots/blob/abf166444763f8aebd6052a527a8119eb39704cf/pdfannots.py#L35
... but I'm not sure how you would usefully represent those in a text output format?

**Comment by balandongiv** [comment]
Thanks for pointing the code snapshot. Apparently, no text output is generated even though we make an arrow line below a text.
