### ISSUE TITLE
PDF example that can illustrate transformation of a text into a blockquote, and the comment into subsequent paragraphs.

### ISSUE THREAD

**Issue by balandongiv** [0xabu/pdfannots#32]
Hi, is there any good pdf file that can represent the case example for the following line

https://github.com/0xabu/pdfannots/blob/abf166444763f8aebd6052a527a8119eb39704cf/pdfannots.py#L384

**Comment by 0xabu** [comment]
No example (I need to get a test suite going), but you should think of this as the default case where you've either written a multi-paragraph comment, or you've selected some text in the PDF and written a non-trivial comment to annotate it.

**Comment by 0xabu** [comment]
You can see some examples of this output in the test file I recently added (tests/hotos17.pdf). Using the default settings gives output such as:
```
 * Page 2 (Background: x86 extensions):
   > user-mode access to FS/GS registers, and TLB tags for non-VM address spaces

   This is lower in column 1
```
