### ISSUE TITLE
Can the code be modified to change the format?

### ISSUE THREAD

**Issue by dummifiedme** [0xabu/pdfannots#34]
I wanted to the output in a certain format for my personal use. Is it possible to have it as I would like? 
Also, is it possible to extract the colour of the highlight or the comment box? So that I can have different formatting based on a colour?

**Comment by 0xabu** [comment]
First entry in the FAQ:

## I'd like to change how the output is formatted.

Some minor changes (e.g.: word wrap, skipping sections) can be accomplished
via command-line arguments. See `pdfannots.py --help`.

All of the output comes from the `PrettyPrinter` class; more elaborate changes
can probably be accomplished there.


... long term I'd like to find a more template-driven approach, but for now you just have to hack it yourself.

**Comment by dummifiedme** [comment]
Got it :)
Thanks
