### ISSUE TITLE
Assertion and TypeError

### ISSUE THREAD

**Issue by balandongiv** [0xabu/pdfannots#37]
Great work from the author.
While other pdf work like a charm, I have issue when running over this  [pdf](https://github.com/0xabu/pdfannots/files/6418921/ab.pdf).

The compiler return an error

```
line 341, in format_bullet
    assert quotepos + quotelen <= len(paras)
AssertionError
```

While disabling the line 341 allow the program run, but,

the compiler throw an error while commented the `assert quotepos + quotelen <= len(paras)`

```
line 675, in main
    paper_title_long=comb_details_report[paper_title_index]['all_text']
TypeError: list indices must be integers or slices, not NoneType
```

**Comment by 0xabu** [comment]
Hi, sorry for the long delay, but were you using some private changes to the script? The first error you mentioned is my code, but the line numbers are off by a bit. The second error is not code I've ever had in the version of the script in this repo.

**Comment by balandongiv** [comment]
Hi, If i recall correctly,  I might had changed part of the code

**Comment by 0xabu** [comment]
I tested the current version with your PDF, and (at least in the default configuration) there were two highlights and no crash. Please feel free to reopen if you can repro.
