### ISSUE TITLE
register at pip?

### ISSUE THREAD

**Issue by chrisgrieser** [0xabu/pdfannots#38]
This little script is great. I built an [Alfred workflow](https://github.com/chrisgrieser/pdf-annotation-extractor-alfred) around pdfannots to have a more convenient UI. 

I want to share it with some colleagues but the whole setup (install python3, pip, pdfminer.six, pdfannots, Alfred with Powerpack, my workflow) is a bit tedious for the less technically adept ones. Could pdfannots just be registered at pip? It would make it a bit easier for others to set it up with a oneliner à la
`pip install pdfannots`

**Comment by 0xabu** [comment]
Done, I think: https://pypi.org/project/pdfannots

**Comment by chrisgrieser** [comment]
Thanks!
