### ISSUE TITLE
Feature Request: Differentiate Extracted Highlights by color

### ISSUE THREAD

**Issue by chrisgrieser** [0xabu/pdfannots#39]
It would be really great to differentiate multi-color highlights in a document. Is that possible on pdfannots' end, or is it rather something that has to be done on pdfminer.six' end?

**Comment by 0xabu** [comment]
It's possible, I haven't had the reason to do it myself yet, but a PR to add such functionality would be welcome, especially the extraction part, i.e. getting the colour into the Annotation object in a useful form.

See #4 and #19 for some previous attempts at this. Now that the output formatting code is more clearly separated from the core, it may be viable to revisit some of this.

**Comment by chrisgrieser** [comment]
I'd happily do it myself, but unfortunately, I do not know any python 🙁
