### ISSUE TITLE
Md output contains highlighted text twice with different formats

### ISSUE THREAD

**Issue by Chris-mik** [0xabu/pdfannots#41]
Thank you very much for this program!
I have run pdfannots via Terminal on Mac OS and in the md output I got some bizarre errors in terms of the formatting.
In all cases, I get the same highlight twice. 
- Example 1: the highlighted text appears in two versions: i) one starting with a blockquote (>) and ii) another without. In the former version the extracted text is more polished, i.e., spaces between words are correct, end-line hyphens are removed and the highlighted text appears as a single sentence, whereas the latter version mixes up word spacing and lines are broken.
- Example 2: the highlighted text appears again in two versions: i) the highlighted text is in "" and ii) the same text starts with --.
I have encountered these issues in the same pdf. I have tried changing various arguments in the pdfannots call function but nothing changed in the output.
The pdf readers that I use to make annotations are: Xodo, Foxit or adobe.

**Comment by 0xabu** [comment]
I'm happy to try to improve the docs or --help output, if you have specific feedback.

--no-group just affects markdown output format, and concretely it selects between the flat MarkdownPrinter and the GroupedMarkdownPrinter implementations

**Comment by Chris-mik** [comment]
Thank you for the detailed response!
I would very much like to help with the documentation, so please let me know how I can contribute.
I have downloaded the folder including your last update, run an extraction from a pdf and I get back the following errors:

      _File "/Users/.../pdfannots.py", line 10, in <module>
        sys.exit(main())
      File "/Users/.../pdfannots/cli.py", line 141, in main
        doc = process_file(
      File "/Users/.../pdfannots/__init__.py", line 448, in process_file
        annot = _mkannotation(pa.resolve(), page)
      File "/Users/.../pdfannots/__init__.py", line 46, in _mkannotation
        subtype = pa.get('Subtype')
    AttributeError: 'NoneType' object has no attribute 'get'_


The call function used is: python3 pdfannots.py "file_2017.pdf" -o notes.md --print-filename -p
The md output is blank.

**Comment by 0xabu** [comment]
For how to "help with documentation", feel free to:
 * submit PRs against the README
 * submit PRs to improve the `--help` output (look in cli.py - it should be fairly obvious how the strings there translate to help output)
