### ISSUE TITLE
Process multiple input files

### ISSUE THREAD

**Issue by thinkbig1979** [0xabu/pdfannots#60]
The description of the "INFILE" argument  is "PDF files to process".

This suggests multiple files can be processed in a batch. Is this correct, and if so:
 - how should the command be formatted (how to specify multiple input files)?
 - will the output file contain a group of annotations per filename?

It would be really useful to be able to do something like:
`pdfannots *.pdf -o allcomments.md`

or have a way to do the same, but to output one file per input file, using the input file name as the output file name.
Perhaps something like this:
`pdfannots *.pdf - multioutput=true -o [filename].md`

Thanks!

**Comment by 0xabu** [comment]
Yes, multiple input files can be processed, producing a single output file, exactly like your first example. This was added by #23, but I don't use the feature myself and never saw huge value over invoking pdfannots multiple times (via shell loops etc.). I think if you're starting to want multiple output files, you would be better off with a shell one-liner.
