### ISSUE TITLE
Support "Caret" annotation

### ISSUE THREAD

**Issue by srenault-list** [0xabu/pdfannots#61]
It would be nice if the program could extract "Caret" annotations as well, which are the opposite of StrikeOut (suggestion of new text within a context).

**Comment by 0xabu** [comment]
Thanks for the suggestion! Do you have an example of a PDF with such annotations?

**Comment by srenault-list** [comment]
Hi, sure. Here is a very basic example with one text addition (insertion) suggestion. 
[1_caret annotation example.pdf](https://github.com/0xabu/pdfannots/files/9889105/1_caret.annotation.example.pdf)

It might be nice if pdfannots could return a bit of context (i.e. some of the text before and after the insertion suggestion) in addition to the text insertion suggestion.

**Comment by 0xabu** [comment]
Quick update on this: the just-merged PR #102 adds some infrastructure for handling Caret annots and produces output for the specific case of a caret&strikeout pair, but doesn't usefully handle the bare insertion case in the example above so this stays open for now. I hope to get to it soon though.

**Comment by 0xabu** [comment]
Now done. The output is a little ugly, but I couldn't think of anything much better.
