### ISSUE TITLE
Add installation to README.md

### ISSUE THREAD

**Issue by another4til7** [0xabu/pdfannots#66]
Expected behavior: running app with help flag produces help file

Actual behavior: produces errors
$ ./pdfannots.py --help
Traceback (most recent call last):
  File "/home/twood/bin/pdf_annots/./pdfannots.py", line 7, in <module>
    from pdfannots.cli import main
  File "/home/twood/bin/pdf_annots/pdfannots/__init__.py", line 13, in <module>
    from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
ModuleNotFoundError: No module named 'pdfminer'

Modify README.md to add "Installing" section including note to:
> sudo pip3 install -r requirements.txt

**Comment by 0xabu** [comment]
The way I expect 99% of users to install this is `pip install pdfannots`, so maybe I'll make that more explicit. For the rest that really want to run from a git clone, pdfminer is listed under dependencies.

**Comment by another4til7** [comment]
I don't do much with Python so I don't have its custom package manager memorized. There's a once where I coded for a living ... now I'm just a guy using a laptop with linux so having an explicit section titled "Installing" or "Setup" is a huge huge time saver.
