### ISSUE TITLE
Feature: Selecting Annotation-Types

### ISSUE THREAD

**Issue by Asbakartz** [0xabu/pdfannots#73]
First of all, I wish to thank you for this incredible CLI-tool, since I have been searching for so long how to extract my own annotations from PDF readings (as a student) for quite some time, and pdfannots works like a charm!

Having said this, I was wondering whether it would be possible to add an option so as to only extract "detailed comments" to a markdown file, or put differently, an option to leave out "highlights".

In my own use case, I tend to highlight the PDF file using different colour schemes for readability, but I am only interested in extracting the comments that I write in the margins of the PDF (so as to add them to my reading notes).

Do you think adding such a feature would be possible, and not to difficult to implement?

**Comment by 0xabu** [comment]
Hi, you should be able to do this already by invoking pdfannots with `--sections=comments`. Feel free to reopen if that doesn't work or I misunderstood.

**Comment by Asbakartz** [comment]
Ohh brilliant, I hadn't noticed it at the top of the user guide when invoking the `--help` command!

Thank you so much for your swift answer, and my apologies for the confusion!
