### ISSUE TITLE
Don't group by annotation type?

### ISSUE THREAD

**Issue by dufferzafar** [0xabu/pdfannots#8]
Showing highlights first, then comments etc. feels a bit odd to me. 

I would much rather have the output sorted by the page / line they're found on.

**Comment by 0xabu** [comment]
The `--no-group` option now does this.

**Comment by dufferzafar** [comment]
Hey, I actually needed this before so I took your source and made a few changes to it: https://github.com/dufferzafar/pdf-ano/

```
Changes:

* Use `docopt` for CLI

* Add support to print only the counts
    + So you can see which documents have any annotations
* Count Ink based annotations
    - Such as the ones generated using Apple Pencil!

* Disabled printing of Page numbers
```
