### ISSUE TITLE
dereference some stuff

### ISSUE THREAD

**Issue by bliep** [0xabu/pdfannots#9]
Needed to dereference some objects to make the code work for some PDFs:

```
@@ -89,6 +89,14 @@ class Annotation:
     def __init__(self, pageno, tagname, coords=None, rect=None, contents=None):
         self.pageno = pageno
         self.tagname = tagname
+
+        if isinstance(coords, pdftypes.PDFObjRef):
+            coords = coords.resolve()
+        if isinstance(rect, pdftypes.PDFObjRef):
+            rect = rect.resolve()
+        if isinstance(contents, pdftypes.PDFObjRef):
+            contents = contents.resolve()
+
         if contents == '':
             self.contents = None
         else:

```

**Comment by 0xabu** [comment]
Thanks! Do you have a PDF you'd be willing to share that demonstrates this issue? It's about time I started collecting a library of test files for issues like this.

**Comment by bliep** [comment]
Sure, here's a sample file from pdfminer where text is highlighted using macos Preview:
[simple1.pdf](https://github.com/0xabu/pdfannots/files/2593095/simple1.pdf)
